# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: ESHOPONWEB-CICD2
trigger:
- master
resources:
 repositories:
   - repository: self
     trigger: none

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: DotNetCoreCLI@2
          displayName: restore
          inputs:
           command: 'restore'
           projects: '**/*.sln'
           feedsToUse: 'select'
         
        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
           command: 'build'
           projects: '**/*.sln'

        - task: DotNetCoreCLI@2
          displayName: Unit-Test	
          inputs:
           command: 'test'
           projects: 'tests/UnitTests/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: publish
          inputs:
           command: 'publish'
           publishWebProjects: true
           arguments: '-o $(Build.ArtifactStagingDirectory'

        - task: PublishBuildArtifacts@1
          displayName: Publish Artifacts
          inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory'
           ArtifactName: RetailApp

